export const blockTypes = {
    "add" : {
        x: 0,
        y: 0,
        width: 35,
        height: 35,
        text: '+',
        fontSize: 20,
        textColor: 'black',
        color: 'lightgreen',
        draggable: true,
        type: 'operator',
        name: 'add',
        numOfInputPorts: 2,
        numOfOutputPorts: 1,
    },
    "multiply" : {
        x: 0,
        y: 0,
        width: 35,
        height: 35,
        text: 'x',
        fontSize: 20,
        textColor: 'black',
        color: 'lightgreen',
        draggable: true,
        type: 'operator',
        name: 'multiply',
        numOfInputPorts: 2,
        numOfOutputPorts: 1,
    },
    "divide" : {
        x: 0,
        y: 0,
        width: 35,
        height: 35,
        text: '÷',
        fontSize: 25,
        textColor: 'black',
        color: 'lightgreen',
        draggable: true,
        type: 'operator',
        name: 'divide',
        numOfInputPorts: 2,
        numOfOutputPorts: 1,
    },
    "gain" : {
        x: 0,
        y: 0,
        width: 50,
        height: 45,
        text: 'Kx',
        fontSize: 20,
        textColor: 'black',
        color: 'lightblue',
        draggable: true,
        type: 'operator',
        name: 'gain',
        numOfInputPorts: 1,
        numOfOutputPorts: 1,
    },
    "integrator" : {
        x: 0,
        y: 0,
        width: 30,
        height: 45,
        text: '∫',
        fontSize: 30,
        textColor: 'black',
        color: 'orange',
        draggable: true,
        type: 'operator',
        name: 'integrator',
        numOfInputPorts: 1,
        numOfOutputPorts: 1,
    },
    "constant" : {
        x: 0,
        y: 0,
        width: 35,
        height: 35,
        text: 'C',
        fontSize: 20,
        textColor: 'white',
        color: 'red',
        draggable: true,
        type: 'source',
        name: 'constant',
        numOfInputPorts: 0,
        numOfOutputPorts: 1,
    },
    "sinusoidal" : {
        x: 0,
        y: 0,
        width: 70,
        height: 35,
        text: 'Sin/Cos',
        fontSize: 13,
        textColor: 'black',
        color: '#CF8FF2',
        draggable: true,
        type: 'source',
        name: 'sinusoidal',
        numOfInputPorts: 0,
        numOfOutputPorts: 1,
    },
    "step" : {
        x: 0,
        y: 0,
        width: 70,
        height: 35,
        text: 'u(t)',
        fontSize: 15,
        textColor: 'black',
        color: '#CF8FF2',
        draggable: true,
        type: 'source',
        name: 'step',
        numOfInputPorts: 0,
        numOfOutputPorts: 1,
    },
    "ramp" : {
        x: 0,
        y: 0,
        width: 70,
        height: 35,
        text: 'r(t)',
        fontSize: 15,
        textColor: 'black',
        color: '#CF8FF2',
        draggable: true,
        type: 'source',
        name: 'ramp',
        numOfInputPorts: 0,
        numOfOutputPorts: 1,
    },
    "display" : {
        x: 0,
        y: 0,
        width: 70,
        height: 35,
        text: 'display',
        fontSize: 15,
        textColor: 'black',
        color: '#F2ED8F',
        draggable: true,
        type: 'sink',
        name: 'display',
        numOfInputPorts: 1,
        numOfOutputPorts: 0,
    }
};

