export const blockTypes = {
    "add" : {
        x: 0,
        y: 0,
        width: 35,
        height: 35,
        text: '+',
        fontSize: 20,
        textColor: 'black',
        color: 'lightgreen',
        draggable: true,
        type: 'add',
    },
    "multiply" : {
        x: 0,
        y: 0,
        width: 35,
        height: 35,
        text: 'x',
        fontSize: 20,
        textColor: 'black',
        color: 'lightgreen',
        draggable: true,
        type: 'multiply',
    },
    "divide" : {
        x: 0,
        y: 0,
        width: 35,
        height: 35,
        text: '÷',
        fontSize: 25,
        textColor: 'black',
        color: 'lightgreen',
        draggable: true,
        type: 'divide',
    },
    "gain" : {
        x: 0,
        y: 0,
        width: 50,
        height: 45,
        text: 'Kx',
        fontSize: 20,
        textColor: 'black',
        color: 'lightblue',
        draggable: true,
        type: 'gain',
        shape: 'rect',
    },
    "integrator" : {
        x: 0,
        y: 0,
        width: 30,
        height: 45,
        text: '∫',
        fontSize: 30,
        textColor: 'black',
        color: 'orange',
        draggable: true,
        type: 'integrator',
    },
    "constant" : {
        x: 0,
        y: 0,
        width: 35,
        height: 35,
        text: 'C',
        fontSize: 20,
        textColor: 'white',
        color: 'red',
        draggable: true,
        type: 'constant',
    },
    "sinusoidal" : {
        x: 0,
        y: 0,
        width: 70,
        height: 35,
        text: 'Sin/Cos',
        fontSize: 13,
        textColor: 'black',
        color: '#CF8FF2',
        draggable: true,
        type: 'sinusoidal',
    },
    "step" : {
        x: 0,
        y: 0,
        width: 70,
        height: 35,
        text: 'u(t)',
        fontSize: 15,
        textColor: 'black',
        color: '#CF8FF2',
        draggable: true,
        type: 'step',
    },
    "ramp" : {
        x: 0,
        y: 0,
        width: 70,
        height: 35,
        text: 'r(t)',
        fontSize: 15,
        textColor: 'black',
        color: '#CF8FF2',
        draggable: true,
        type: 'ramp',
    },
    "display" : {
        x: 0,
        y: 0,
        width: 70,
        height: 35,
        text: 'display',
        fontSize: 15,
        textColor: 'black',
        color: '#F2ED8F',
        draggable: true,
        type: 'display',
    }
};

